Super starter v2
SuperFarmDAO/SuperFarm-Contracts pull request #17
Opened 2021-09-10 06:44 UTC by letsleroyu

Updated superStarter.sol 

- Removed all references to Upgradable, Initializaible
- Changed safeTranfserFrom to safeTransfer in the necessary places.
- Added/changed the admin functions
- Added ReentrancyGuard

2021-09-10 20:06 UTC, TimTinkers requested changes

2021-09-10 20:06 UTC, TimTinkers commented on contracts/SuperStarter.sol
> +    function sweep(IERC20 _token, address _recepient) external onlyOwner {
Instead of reimplementing this here, let's inherit this from `Sweepable`.

2021-09-13 04:06 UTC, letsleroyu commented
Just updated SuperStater.sol contract. 
I also changed the error text in the sweep function, it seems to me because the Sweep contract is used not only in MintShop, it is better to make the text more informative.

2021-09-14 08:25 UTC, TimTinkers commented
> 
> 
> Just updated SuperStater.sol contract.
> I also changed the error text in the sweep function, it seems to me because the Sweep contract is used not only in MintShop, it is better to make the text more informative.

Excellent, and good catch.

2021-09-14 08:27 UTC, TimTinkers approved these changes

2021-09-14 08:27 UTC, merged